### ISSUE TITLE
Add AccountNames and MosaicNames endpoints

### ISSUE THREAD

**Issue by rg911** [nemtech/nem2-sdk-java#72]
`GetAccountNames` and `GetMosaicNames` are new endpoints introduced in `Dragon`

**Comment by fboucquez** [comment]
I have found inconsistencies between the open API spec and the rest service I am discussing with @dgarcia360. 

There is definitely a bug in catapult rest

![image](https://user-images.githubusercontent.com/5390558/63343752-0679f780-c34f-11e9-81ec-527659f96c26.png)

Although those methods should return a list instead of an object with a list field, David is updating the open api specification to match the current reponses.
